### ISSUE TITLE
Bug: Items out of sync in-game

### ISSUE THREAD

**Issue by ptaranat** [fjallnari/morii-vtt#103] opened 2023-02-04 18:52 UTC
Items disappear after being added. Maybe if the GM is viewing the player's sheet, changes are not saved.

**Comment by Ashmogh** [comment] 2023-02-06 00:59
This bug's tricky. I've used to have it happen in the past, but haven't seen it since the last Sockets refactor. I believe it has to do with there being two versions of the same sheet (GM and player) where if an edit happens on either side, the old version sometimes for some reason overwrites the newly edited one. Have to test it more thouroughly to find the exact situation and the root cause.

**Comment by ptaranat** [comment] 2023-02-06 01:24
Reminds me of a similar problem https://stackoverflow.com/questions/31092669/how-does-google-docs-deal-with-editing-collisions

agree we should verify first

**Comment by Ashmogh** [comment] 2023-02-12 19:28
I might have fixed this issue with 44cc5be, which solved character sheet changes sometimes not actually triggering the submit event leading to differences between character sheet versions. 

I couldn't reproduce the items disappearing both before and after this fix though, so I'm hesitant to close this.

**Comment by ptaranat** [comment] 2023-02-13 21:55
Let's playtest it for a couple games with the GM viewing the sheets. If it works, we can close it. Locally, I no longer see the bug if I am testing as GM and player, but we may have to deal with some intercontinental latency in prod.

**Comment by fjallnari** [comment] 2023-04-16 22:07
I will close this issue for now, as I've not had it happen for the last three playtests we've done. If it ever comes up again, we can re-open this.

**Closed by fjallnari** 2023-04-16 22:07 UTC
Labels: bug
